/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-SOCI.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : SOCI
 #	author : miyako
 #	2025/05/20
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-SOCI.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- SOCI
            
			case 1 :
				SOCI(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void SOCI(PA_PluginParameters params) {

}

