/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-SOCI.h
 #	source generated by 4D Plugin Wizard
 #	Project : SOCI
 #	author : miyako
 #	2025/05/20
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SOCI_H
#define PLUGIN_SOCI_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#include "C_TEXT.h"

#include "soci/soci.h"
#include "soci/sqlite3/soci-sqlite3.h"

#include <memory> //for std::unique_ptr

typedef enum {
    soci_backend_odbc       = 0,
    soci_backend_mysql      = 1,
    soci_backend_postgresql = 2,
    soci_backend_sqlite3    = 3
    
}soci_backend_t;

typedef enum {
    soci_mode_none          = 0,
    soci_mode_transaction   = 1
}soci_mode_t;


#pragma mark -

static void SOCI(PA_PluginParameters params);

#endif /* PLUGIN_SOCI_H */
