/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-SOCI.h
 #	source generated by 4D Plugin Wizard
 #	Project : SOCI
 #	author : miyako
 #	2025/05/20
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SOCI_H
#define PLUGIN_SOCI_H

#include "4DPluginAPI.h"

#pragma mark -

void SOCI(PA_PluginParameters params);

#endif /* PLUGIN_SOCI_H */
